main: main.Main
name: LTHardcore
author: EggyRepublic
version: A1.1.1
description: Anti-heal   
api-version: 1.16
commands:
  hardcore:
    description: toggle player's regen capabilities
    usage: /hardcore [player name] or /hardcore info [player name]